### ISSUE TITLE
Issue with msgpack and echo server

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ruby#161]
### Case 1

`git checkout add-jwt-test`
`rspec ./spec/acceptance/realtime/auth_spec.rb:1198`

Test passes, both in json and msgpack.

### Case 2

Change `auth_url` [this line](https://github.com/ably/ably-ruby/pull/137/files#diff-234b86ab2ae4f25eac36170940dfb2b1R1036) to `https://echo.ably.io/createJWT`

and the test fails, but (here's the weird part) ONLY when the protocol is `msgpack`

Relevant log:

```
----------------------------------
Verbose Ably log from test failure
----------------------------------
14:02:29.737 [debug] Ably::Realtime::Connection: Transitioned to connecting14:02:29.738 [debug] Ably::Realtime::Connection: StateEmitter changed from STATE.Initialized => connecting
14:02:29.738 [debug] ConnectionManager: Opening a websocket transport connection
14:02:29.749 [debug] ConnectionManager: Setting up automatic connection timeout timer for 10s
14:02:29.927 [debug] Auth: new token following authorisation: <TokenDetails token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NDksIm
V4cCI6MTUyODM3Mjk4NH0.bCoNd31gFVIVf1xq4IIyOU3wK6DOy7Jal29vvJ3q6Sk client_id= key_name= issued= expires= capability= expired?=false>
14:02:29.928 [debug] Connection: Opening socket connection to sandbox-realtime.ably.io:443/?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJ
pYXQiOjE1MjgzNzI5NDksImV4cCI6MTUyODM3Mjk4NH0.bCoNd31gFVIVf1xq4IIyOU3wK6DOy7Jal29vvJ3q6Sk&format=msgpack&echo=true&v=1.0&lib=ruby-1.0.6&heartbeats=false
14:02:29.928 [debug] Connection: EventMachine connecting to sandbox-realtime.ably.io:443 with URL: wss://sandbox-realtime.ably.io:443?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NDksImV4cCI6MTUyODM3Mjk4NH0.bCoNd31gFVIVf1xq4IIyOU3wK6DOy7Jal29vvJ3q6Sk&format=msgpack&echo=true&v=1.0&lib=ruby-1.0.6&heartbeats=false
14:02:29.964 [debug] Ably::Realtime::Connection::WebsocketTransport: StateEmitter changed from STATE.Initialized => STATE.Connecting
14:02:30.018 [debug] Ably::Realtime::Connection::WebsocketTransport: StateEmitter changed from STATE.Connecting => STATE.Connected
14:02:30.194 [debug] WebsocketTransport: socket opened to wss://sandbox-realtime.ably.io:443?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NDksImV4cCI6MTUyODM3Mjk4NH0.bCoNd31gFVIVf1xq4IIyOU3wK6DOy7Jal29vvJ3q6Sk&format=msgpack&echo=true&v=1.0&lib=ruby-1.0.6&heartbeats=false, waiting for Connected protocol message
14:02:30.242 [debug] WebsocketTransport: Prot msg recv <=: ACTION.Connected - {"action"=>4, "connectionId"=>"fLxzp4DX6d", "connectionKey"=>"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP", "connectionSerial"=>-1, "connectionDetails"=>{"connectionKey"=>"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP", "maxMessageSize"=>16384, "maxInboundRate"=>250, "maxOutboundRate"=>100, "maxFrameSize"=>262144, "serverId"=>"frontend.e790.2.eu-west-2-A.i-0ee3e071afb79e275", "connectionStateTtl"=>120000, "maxIdleInterval"=>15000}}
14:02:30.242 [debug] ACTION.Connected received: {"action":4,"connectionId":"fLxzp4DX6d","connectionKey":"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP","connectionSerial":-1,"connectionDetails":{"connectionKey":"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP","maxMessageSize":16384,"maxInboundRate":250,"maxOutboundRate":100,"maxFrameSize":262144,"serverId":"frontend.e790.2.eu-west-2-A.i-0ee3e071afb79e275","connectionStateTtl":120000,"maxIdleInterval":15000}}
14:02:30.243 [debug] ConnectionManager: New connection created with ID fLxzp4DX6d and key e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP
14:02:30.243 [debug] Ably::Realtime::Connection: Transitioned from connecting => connected
14:02:30.243 [debug] Ably::Realtime::Connection: StateEmitter changed from STATE.Connecting => connected
14:02:34.024 [debug] WebsocketTransport: Prot msg recv <=: ACTION.Auth - {"action"=>17}
14:02:34.024 [debug] ACTION.Auth received: {"action":17}
14:02:34.239 [debug] Auth: new token following authorisation: <TokenDetails token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NTQsImV4cCI6MTUyODM3Mjk4OX0.pji6_8JBlOskd7mw2ilqv-NAFcznKisIkjxiVQP8__M client_id= key_name= issued= expires= capability= expired?=false>
14:02:34.239 [debug] Performing inline AUTH with Ably using token <TokenDetails token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NTQsImV4cCI6MTUyODM3Mjk4OX0.pji6_8JBlOskd7mw2ilqv-NAFcznKisIkjxiVQP8__M client_id= key_name= issued= expires= capability= expired?=false>
14:02:34.239 [debug] Connection: Prot msg queued =>: ACTION.Auth {"action":17,"auth":{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NTQsImV4cCI6MTUyODM3Mjk4OX0.pji6_8JBlOskd7mw2ilqv-NAFcznKisIkjxiVQP8__M"}}
14:02:34.240 [debug] WebsocketTransport: Prot msg sent =>: ACTION.Auth {"action":17,"auth":{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il90bXBfYWRzT1l3LjFYRHFVQSJ9.eyJpYXQiOjE1MjgzNzI5NTQsImV4cCI6MTUyODM3Mjk4OX0.pji6_8JBlOskd7mw2ilqv-NAFcznKisIkjxiVQP8__M"}}
14:02:45.237 [debug] Ably::Realtime::Connection: Transitioned from connected => closing
14:02:45.237 [debug] Ably::Realtime::Connection: StateEmitter changed from STATE.Connected => closing
14:02:45.237 [debug] Connection: Prot msg queued =>: ACTION.Close {"action":7}
14:02:45.238 [debug] Ably::Realtime::Connection::WebsocketTransport: StateEmitter changed from STATE.Connected => STATE.Disconnected
14:02:45.238 [debug] ConnectionManager: Unsubscribed from all events from current transport
14:02:45.238 [debug] Ably::Realtime::Connection: Transitioned from closing => closed
14:02:45.238 [debug] Ably::Realtime::Connection: StateEmitter changed from STATE.Closing => closed

          client reauths correctly without going through a disconnection (FAILED - 1)


...


Failures:

  1) Ably::Realtime::Auth using MsgPack protocol when using JWT when JWT token expires and an AUTH procol message is received client reauths correctly without going through a disconnection
     Failure/Error:
       ::EventMachine.run do
         yield
       end

     Timeout::Error:
       execution expired
     # ./spec/support/event_machine_helper.rb:15:in `block in run_reactor'
     # ./spec/support/event_machine_helper.rb:14:in `run_reactor'
     # ./spec/support/event_machine_helper.rb:128:in `block (3 levels) in <top (required)>'
     # ./spec/support/rest_testapp_before_retry.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/support/event_machine_helper.rb:135:in `block (2 levels) in <top (required)>'

Finished in 23.58 seconds (files took 3.63 seconds to load)
2 examples, 1 failure
```

I could not spot anything wrong in the log of the failure.
Do you have any idea @mattheworiordan @SimonWoolf ?

UPDATE: see ]Simon's comment](https://github.com/ably/ably-ruby/issues/161#issuecomment-395425569) below.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-463) by [Unito](https://www.unito.io)

**Comment by SimonWoolf** [comment]
The access token appears to be being encoded by msgpack as BIN, rather than STR. So realtime is failing to read it.
This is possibly a realtime bug, as realtime should probably be lenient and accept tokens as BIN. But it's also arguably a bug in ably-ruby, which assuming the echoserver returns a jwt token with a content-type of `text/plain`, should be treating it as text, in which case msgpack should be encoding it as STR.

**Comment by funkyboy** [comment]
@SimonWoolf Thanks. I am confused tho.

If "realtime is failing to read it" the connection shouldn't even succeed right? We shouldn't see

`14:02:30.242 [debug] WebsocketTransport: Prot msg recv <=: ACTION.Connected - {"action"=>4, "connectionId"=>"fLxzp4DX6d", "connectionKey"=>"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP", "connectionSerial"=>-1, "connectionDetails"=>{"connectionKey"=>"e02U5rLrQAL2DP!fLxzp4DX6d0nKgYI-10682e02U5rLrQAL2DP", "maxMessageSize"=>16384, "maxInboundRate"=>250, "maxOutboundRate"=>100, "maxFrameSize"=>262144, "serverId"=>"frontend.e790.2.eu-west-2-A.i-0ee3e071afb79e275", "connectionStateTtl"=>120000, "maxIdleInterval"=>15000}}
`

**Comment by SimonWoolf** [comment]
> If "realtime is failing to read it" the connection shouldn't even succeed right?

The connection is succeeding initially because in the initial connection, the token is sent in the querystring params. These are part of the url, they're not msgpack-encoded, they're just text. So the issue is only when the token is msgpack-encoded and sent in a protocol message, as part of the online reauth (which is what 1198 is testing).

**Comment by paddybyers** [comment]
> This is possibly a realtime bug, as realtime should probably be lenient and accept BIN tokens. But it's also arguably a bug in ably-ruby, which (assuming the echoserver returns a jwt token with a content-type of text/plain) should be treating it as text, in which case msgpack should be encoding it as STR.

Personally I think it's a library bug, but here's a blind fix for realtime anyway: https://github.com/ably/realtime/commit/48385f3d624b07358094a3cfde688b78d28e32ce

**Comment by SimonWoolf** [comment]
Fixed on the realtime side by https://github.com/ably/realtime/pull/1797 . @funkyboy I'll leave this issue open for you to investigate and fix on the library side.

**Comment by mattheworiordan** [comment]
@funkyboy is this still an issue?

**Comment by funkyboy** [comment]
@mattheworiordan [This is the last build of `master`](https://travis-ci.org/ably/ably-ruby/builds/406838406) and everything is green in the msgpack case. 
Having been [fixed in realtime](
https://github.com/ably/realtime/pull/1797) it's likely gonna be hard to reproduce this. 

Technically it's still an issue, but probably hard to reproduce/fix now.

**Comment by mattheworiordan** [comment]
When you say technically it's still an issue, I am assuming you mean what @SimonWoolf said is the issue:

> The access token appears to be being encoded by msgpack as BIN, rather than STR

If so, it shouldn't be hard to detect that surely with a mock?  Either way, I think this issue should be updated to explain exactly what the problem is in the body, or we should close and perhaps create a low priority issue to resolve in future?

**Comment by funkyboy** [comment]
@mattheworiordan Updated the description and the labels.

**Comment by TheSmartnik** [comment]
Issue no longer reproducible
1. Branch `add-jwt-test` has been merged
2. `auth_url` in [this line](https://github.com/ably/ably-ruby/pull/137/files#diff-234b86ab2ae4f25eac36170940dfb2b1R1036) points nowhere
3. Case 2 contains the name of the failing spec. Its current url is `https://echo.ably.io/createJWT` and it's passing fine
